# Домашнее задание. Семинар 10

### Задание 44 
В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?


import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI'lst})
data.head()

In [41]:
import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  human
1  robot
2  human
3  robot
4  robot

In [42]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(handle_unknown='ignore')
encoder_df = pd.DataFrame(encoder. fit_transform(data[['whoAmI']]). toarray ())
final_df = data.join (encoder_df)
final_df.drop('whoAmI', axis= 1 , inplace= True )
final_df.columns = ['human', 'robot']

final_df

    human  robot
0     1.0    0.0
1     0.0    1.0
2     1.0    0.0
3     0.0    1.0
4     0.0    1.0
5     1.0    0.0
6     0.0    1.0
7     1.0    0.0
8     0.0    1.0
9     1.0    0.0
10    0.0    1.0
11    1.0    0.0
12    0.0    1.0
13    0.0    1.0
14    1.0    0.0
15    1.0    0.0
16    1.0    0.0
17    0.0    1.0
18    1.0    0.0
19    0.0    1.0